name: "Dropbox Large File Uploader"
description: "A GitHub Action to upload large files to Dropbox using a refresh token."
author: "Defaultman"
runs:
  using: "docker"
  image: "Dockerfile"

inputs:
  app_key:
    description: "Dropbox API app key."
    required: true
  app_secret:
    description: "Dropbox API app secret."
    required: true
  refresh_token:
    description: "Dropbox API refresh token."
    required: true
  file_path:
    description: "Path to the file to upload."
    required: true
  dropbox_path:
    description: "Destination path in Dropbox."
    required: true
  write_mode:
    description: "Write mode is one of 'add', 'overwrite', or 'update' as defined in https://www.dropbox.com/developers/documentation/http/documentation#files-upload_session-finish
    required: false
    default: 'add'

branding:
  icon: "package"
  color: "blue"
