name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: latchkey-466917
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/latchkey-466917/dropbox-large-file-uploader:${{ github.sha }} -f Dockerfile .
          docker tag gcr.io/latchkey-466917/dropbox-large-file-uploader:${{ github.sha }} gcr.io/latchkey-466917/dropbox-large-file-uploader:latest

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/latchkey-466917/dropbox-large-file-uploader:${{ github.sha }}
          docker push gcr.io/latchkey-466917/dropbox-large-file-uploader:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy dropbox-large-file-uploader \
            --image gcr.io/latchkey-466917/dropbox-large-file-uploader:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars="NODE_ENV=production" \
            --memory=1Gi \
            --cpu=1 \
            --concurrency=80 \
            --max-instances=10 \
            --port=${{ secrets.PORT || '3000' }}

      - name: Output service URL
        run: |
          echo "Service deployed to: $(gcloud run services describe dropbox-large-file-uploader --region=us-central1 --format='value(status.url)')"
